### ISSUE TITLE
CI: Hardhat image

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-studio#744]
We are distributing our hardhat image in dockerhub [https://hub.docker.com/r/yeagerai/simulator-hardhat/tags](https://hub.docker.com/r/yeagerai/simulator-hardhat/tags)

And there are some things that make it a bit tedious to manage when importing

## Many volumes

Currently there are all of these mappings:

```
...
    volumes:
      - ./hardhat/contracts:/app/contracts
      - ./hardhat/scripts:/app/scripts
      - ./hardhat/test:/app/test
      - ./hardhat/hardhat.config.js:/app/hardhat.config.js
      - hardhat_artifacts:/app/artifacts
...
volumes:
  hardhat_artifacts:
```

Can't we just have one volume mapping like

```
    volumes:
      - ./hardhat:/app/hardhat
```

?

## Healthcheck

The health check is currently done in the `docker-compose.yml`. Can it be done in the Dockerfile so it's distributed with the image out of the box?

```
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "-H", "Content-Type: application/json", "--fail", "http://localhost:8545", "-d", '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
```

## Dockerfile.hardhat

Can we have the default envvar with `ENV HARDHAT_NETWORK=hardhat` instead of in the docker-compose.yml?

```
    environment:
      - HARDHAT_NETWORK=hardhat
```

lstl
